[package]
name = "proxy_lib"
version = "0.1.0"
authors = ["Damian Andrei <andreidaamian@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
bytes = "0.5.4"
byteorder = "1.3.4"
flate2 = "1.0.13"
num_enum = "0.4.3"
polling = "2.2.0"