[package]
name = "dune"
version = "0.1.0"
authors = ["Damian Andrei <andreidaamian@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.26"
proxy_lib = { path = "../proxy_lib" }
serde_json = "1.0.79"